name: azure-app-registration-monitor
on:
  workflow_dispatch:

run-name: azure-app-registration-monitor
jobs:
  azure-app-registration-monitor:
    runs-on: ubuntu-latest

    steps:
      - name: checout code
        uses: actions/checkout@v4
      - name: set up python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: package installations
        run: |
          pip install poetry
          poetry install
      - name: execute python program
        env:
          AZURE_CLIENT_ID: ${{ secrets.OWNER_SP_APP_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.OWNER_SP_APP_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          poetry run python3 app_registrations.py
      - name: Completed
        run: |
          echo "program completed successfully"